version: '3'
services:
    java-maven-app:
        image: josmbrio/my-repo:jma-2.0
        ports:
            - 8080:8080
    postgres:
        image: postgres:latest
        port:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD: my-pass
